### ISSUE TITLE
No images

### ISSUE THREAD

**Issue by dreadric** [qinyuanpei/zngirls#1]
When loading newer albums, the images is text: zngirls.com. Could you fix please? Thank you.

**Comment by qinyuanpei** [comment]
I am sure the image files can be downloaded 😄

**Comment by qinyuanpei** [comment]
This website change the domain, but new domain will redirect to origin domain

**Comment by dreadric** [comment]
How do i make it so that it can detect the new domain? New domain is https://t1.onvshen.com:85. I try adding tems=soup.find("div",class_="gallery_wrapper").find_all("img", "t1") but it doesn't work.

**Comment by qinyuanpei** [comment]
Fixed！
